name: linting

on:
  pull_request:

jobs:
  golangci:
    name: coverage and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.22"
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - run: go test ./... -cover
